working_directory: ./examples/example_modules
test_working_directory: ./examples/example_modules/adder
command: go run main.go
fix_file: adder/adder.go
test_file: adder/adder_test.go
timeout_seconds: 30
max_iterations: 4
environment: # optional environment variables
