working_directory: ./examples/example_server # This path should point to the directory where your go.mod file is
command: go run main.go # Specify your main file to run
timeout_seconds: 5
max_iterations: 4
environment: # optional environment variables
