working_directory: ./examples/example_simple # This path should point to the directory where your go.mod file is
command: go run main.go # Specify your main file to run
fix_file: main.go # This is now optional, the file to fix
timeout_seconds: 30
max_iterations: 4
environment: # optional environment variables
